Create CLI for managing ACLs
Also includes:

* Get jest coverage working (did not print coverage results before)
* Opportunistic tweaks to `package.json`:
  * Add mjgiarlo as contributor
  * Remove apparently defunct `main` entry
  * Run `eslint` on all .js files (future-proofing in case we add dirs)
  * Remove `--runInBand` arg from jest invocations (unnecessary AFAICT?)
  * Add `jest-integration` npm script, setting up near-term integration work

**Note 1**: I chose to use `commander` for the CLI since it's both featureful and maintained unlike some of the other libraries mentioned in #4.

**Note 2**: I considered using `npm run` instead of `bin/...` for this, but so far I'm preferring the `bin/...` approach to distinguish it from the developer experience of running stuff with `npm run`.

**Note 3**: Due to the way `commander` is tested (using another process per a recipe found on Google), none of the coverage added in this branch is picked up by static analysis. Sad trombone. But it's there

Here's how the CLI looks from the user perspective.

Print help if no commands or options provided:

```shell
$ bin/acl
Usage: acl [options] [command]

Options:
  -v, --version          output the version number
  -h, --help             output usage information

Commands:
  users <group>          List users and access controls in a group
  groups                 List all groups
  add <user> <group>     Add user to group
  remove <user> <group>  Remove user from group
```

Print help when requested (also works with `-h`):

```shell
bin/acl --help
Usage: acl [options] [command]

Options:
  -v, --version          output the version number
  -h, --help             output usage information

Commands:
  users <group>          List users and access controls in a group
  groups                 List all groups
  add <user> <group>     Add user to group
  remove <user> <group>  Remove user from group
```

Print version of acl tool (taken from package.json):

```shell
$ bin/acl -v
0.0.1
```

Show all groups:

```shell
$ bin/acl groups
not implemented yet
```

Throw an error when required argument is missing:

```shell
$ bin/acl users
error: missing required argument `group'
```

List all users in a group:

```shell
$ bin/acl users http://foo.bar
list() called with http://foo.bar
[ 'http://sinopia.io/users/cmharlow' ]
```

Add a user to a group:

```shell
$ bin/acl add userURI groupURI
adding userURI to groupURI
not implemented yet
```

Remove a user from a group:

```shell
$ bin/acl remove userURI groupURI
removing userURI to groupURI
not implemented yet
```

fixes #4